import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
const mondayApiUrl="https://api.monday.com/v2";
const corsHeaders={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS"};
type Col={id:string;title:string;type:string;settings_str?:string};
Deno.serve(async(req)=>{if(req.method==="OPTIONS")return new Response("ok",{headers:corsHeaders});const supabase=createClient(Deno.env.get("SUPABASE_URL")!,Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!);const mondayToken=Deno.env.get("MONDAY_API_TOKEN");if(!mondayToken)return json({error:"Missing MONDAY_API_TOKEN"},500);const body=await req.json().catch(()=>({}));const sceneId=clean(body.sceneId),shareToken=clean(body.shareToken);if(!sceneId&&!shareToken)return json({error:"Missing scene identifier"},400);let isAdmin=false;const accessToken=(req.headers.get("Authorization")||"").replace(/^Bearer\s+/i,"");if(accessToken){const {data:authData}=await supabase.auth.getUser(accessToken);if(authData?.user?.id){const {data:adminUser}=await supabase.from("admin_users").select("user_id").eq("user_id",authData.user.id).maybeSingle();isAdmin=!!adminUser}}let q=supabase.from("scenes").select("*, scene_items(*)").limit(1);q=sceneId?q.eq("id",sceneId):q.eq("share_token",shareToken);const {data:scenes,error}=await q;if(error)return json({error:error.message},500);const scene=scenes?.[0];if(!scene)return json({error:"Scene not found"},404);if(!isAdmin&&(!shareToken||scene.share_token!==shareToken))return json({error:"Forbidden"},403);const boardId=clean(scene.monday_board_id),itemId=clean(scene.monday_item_id);if(!boardId||!itemId)return json({synced:false,reason:"Scene has no Monday link"});const cols=await boardColumns(mondayToken,boardId);const tasks=updates(scene,cols,mondayToken,boardId,itemId);const results=await Promise.allSettled(tasks.map(t=>t.promise));const failed=results.map((r,i)=>({r,title:tasks[i]?.title||"Update"})).filter(e=>e.r.status==="rejected").map(e=>`${e.title}: ${String((e.r as PromiseRejectedResult).reason?.message||(e.r as PromiseRejectedResult).reason||"Erreur Monday")}`);return json({synced:failed.length===0,updates:tasks.length-failed.length,failed_updates:failed,board_id:boardId,offer:scene.offer},failed.length?207:200)});
function updates(scene:any,cols:Col[],token:string,boardId:string,itemId:string){const opt=scene?.source_payload?.options||{},pricing=scene?.source_payload?.pricing||{};const items=(scene?.scene_items||[]).map((r:any)=>({...r.config,type:r.type,label:r.label||r.config?.label}));const out:any[]=[];status(out,token,boardId,itemId,col(cols,["ÉTAPE 1","ETAPE 1"]),"CONFIG EFFECTUÉ");const moq=col(cols,["MOQUETTE"]);status(out,token,boardId,itemId,moq,carpet(moq,opt));const emp=col(cols,["EMPREINTE"]);status(out,token,boardId,itemId,emp,footprint(emp,opt));const coton=col(cols,["COTON"]);status(out,token,boardId,itemId,coton,wall(coton,opt));const counter=findCounter(items);const comp=col(cols,["COMPTOIR"]);status(out,token,boardId,itemId,comp,counterStatus(comp,counter));const sign=col(cols,["SIGNA COMPTOIR","SIGNA BANQUE"]);status(out,token,boardId,itemId,sign,counterSign(sign,counter));const cover=col(cols,["VISUEL 2,5M²","VISUEL 2,5M2","BACHE","BÂCHE"]);if(cover)status(out,token,boardId,itemId,cover,wallCover(cover,opt));const arche=col(cols,["ARCHE"]);if(arche)status(out,token,boardId,itemId,arche,yesno(arche,items.some((i:any)=>norm(`${i.type} ${i.label}`).includes("ARCHE"))));const pac=col(cols,["PACMAN Ø1000","PACMAN"]);if(pac)status(out,token,boardId,itemId,pac,yesno(pac,items.some((i:any)=>norm(`${i.type} ${i.label}`).includes("PACMAN"))));const vis=col(cols,["VISCOM SUSPENDU Ø1600","VISCOM CLOISON Ø1120","VISCOM"]);if(vis)status(out,token,boardId,itemId,vis,visualObject(vis,items,"VISCOM"));const video=col(cols,["VIDEO","VIDÉO"]);if(video)status(out,token,boardId,itemId,video,items.some((i:any)=>norm(`${i.type} ${i.label}`).includes("VIDEO"))?pick(video,["ATT VIDEO","VIDEO OK","OUI"]):pick(video,["NON"]));const am=amco(pricing);const amc=cols.find(c=>c.type==="long_text"&&norm(c.title)==="AMCO")||col(cols,["AMCO"]);if(amc)longtext(out,token,boardId,itemId,amc,am.text);const amce=cols.find(c=>c.type==="numbers"&&norm(c.title).includes("AMCO"));if(amce)number(out,token,boardId,itemId,amce,am.total);return out}
function carpet(c:Col|null,o:any){if(!c)return"";if(o.carpetThick)return pick(c,["EPAISSE","PERSONNALISÉ","PERSONNALISE"]);return pickColor(c,[o.carpetColorName,o.carpetColorReference,o.carpetColorId],["GRIS CLAIR - 0939","PERSONNALISÉ","PERSONNALISE"])}
function footprint(c:Col|null,o:any){if(!c)return"";if(o.carpetFootprintEnabled===false||o.technicalFloorType)return pick(c,["NON"]);return pickColor(c,[o.carpetFootprintColorName,o.carpetFootprintColorReference,o.carpetFootprintColorId],["PERSONNALISÉ","PERSONNALISE"])}
function wall(c:Col|null,o:any){if(!c)return"";return pickColor(c,[o.wallFabricColorName,o.wallFabricColorReference,o.wallFabricColorId],["BLANC - 303","PERSONNALISÉ","PERSONNALISE"])}
function counterStatus(c:Col|null,i:any){if(!c)return"";if(!i||i?.options?.counterHidden)return pick(c,["NON"]);const o=i.options||{},m=norm(o.binary2ColorMode||"");if(!o.binary2ColorName&&!o.binary2ColorReference&&!o.binary2Color&&!m)return pick(c,["BOIS","H3331","H3303"]);const text=norm(`${o.binary2ColorName} ${o.binary2ColorReference}`);if(m.includes("WOOD")||text.includes("BOIS"))return pick(c,["BOIS",o.binary2ColorReference,"H3331","H3303"]);if(m.includes("WHITE")||text.includes("BLANC"))return pick(c,["BLANC","W908"]);return pickColor(c,[o.binary2ColorName,o.binary2ColorReference,o.binary2ColorId],["PERSONNALISÉ","PERSONNALISE"])}
function counterSign(c:Col|null,i:any){if(!c)return"";if(!i||i?.options?.counterHidden)return pick(c,["NON"]);const o=i.options||{};if(o.binary3ImageUrl)return pick(c,["OUI - FICHIER OK","FICHIER OK"]);if(o.binary3VisualPending)return pick(c,["OUI - ATT FICHIER","ATT FICHIER"]);return pick(c,["NON"])}
function wallCover(c:Col|null,o:any){if(!c)return"";const has=Object.values(o.wallCovers||{}).some((v:any)=>!!v?.enabled);return has?pick(c,["OUI - ATT FICHIER","ATT FICHIER","PERSONNALISÉ","PERSONNALISE"]):pick(c,["NON"])}
function visualObject(c:Col|null,items:any[],marker:string){if(!c)return"";const it=items.find(i=>norm(`${i.type} ${i.label}`).includes(norm(marker)));if(!it)return pick(c,["NON"]);const hasFile=Object.values(it.options||{}).some(v=>String(v||"").includes("/storage/"));return hasFile?pick(c,["OUI - FICHIER OK","FICHIER OK"]):pick(c,["OUI - ATT FICHIER","ATT FICHIER","OUI"])}
function yesno(c:Col,on:boolean){return pick(c,[on?"OUI":"NON"])}
function amco(pricing:any){const lines=Array.isArray(pricing?.lines)?pricing.lines:[];const paid=lines.filter((l:any)=>{const t=Number(l?.total||0);return Number.isFinite(t)&&t>0&&!l?.mandatory&&!norm(l?.type||"").includes("MANDATORY FURNITURE INSURANCE")});const total=round(paid.reduce((s:number,l:any)=>s+Number(l.total||0),0));const text=paid.map((l:any)=>`${Number(l.quantity||1)>1?`${Number(l.quantity||1)} × `:""}${clean(l.label)||clean(l.type)||"Option"}${clean(l.reference)?` — ${clean(l.reference)}`:""} : ${money(Number(l.total||0))} HT`).join("\n");return{total,text}}
function findCounter(items:any[]){return items.find(i=>{const t=norm(`${i.type} ${i.label} ${i.options?.variantLabel||""}`);return t.includes("BANQUE")||t.includes("COMPTOIR")||t.includes("ACCUEIL")})||null}
function pickColor(c:Col,vals:any[],fallbacks:string[]=[]){const cand=vals.flatMap(v=>colorCandidates(v));return pick(c,[...cand,...fallbacks])}
function colorCandidates(v:any){const s=clean(v);if(!s)return[];const arr=[s];arr.push(...(s.match(/[A-Z]?\d{3,4}[A-Z]?/gi)||[]));arr.push(s.replace(/color-group-[^:]+:/i,"").replace(/[-_]+/g," "));return arr}
function pick(c:Col|null,cands:any[]){const labs=labels(c),nc=cands.map(norm).filter(Boolean);for(const cand of nc){const e=labs.find(l=>norm(l)===cand);if(e)return e}for(const cand of nc){const p=labs.find(l=>{const v=norm(l);return v.includes(cand)||cand.includes(v)});if(p)return p}return""}
function labels(c:Col|null){if(!c?.settings_str)return[] as string[];try{const s=JSON.parse(c.settings_str),labs=s?.labels||{},pos=s?.labels_positions_v2||{};return Object.keys(labs).sort((a,b)=>Number(pos[a]??999)-Number(pos[b]??999)).map(k=>String(labs[k]||"")).filter(Boolean)}catch{return[] as string[]}}
function col(cols:Col[],titles:string[]){const wanted=titles.map(norm);return cols.find(c=>wanted.includes(norm(c.title)))||cols.find(c=>wanted.some(t=>norm(c.title).includes(t)||t.includes(norm(c.title))))||null}
function status(out:any[],token:string,b:string,i:string,c:Col|null,label:string){if(c&&label)out.push({title:c.title,promise:updateCol(token,b,i,c.id,{label})})}
function longtext(out:any[],token:string,b:string,i:string,c:Col|null,text:string){if(c)out.push({title:c.title,promise:updateCol(token,b,i,c.id,{text:clean(text)})})}
function number(out:any[],token:string,b:string,i:string,c:Col|null,value:number){if(c)out.push({title:c.title,promise:updateSimple(token,b,i,c.id,String(round(value)))})}
async function boardColumns(token:string,boardId:string){const q=`query($ids:[ID!]){boards(ids:$ids){columns{id title type settings_str}}}`;const p=await monday(token,q,{ids:[boardId]});return(p.data?.boards?.[0]?.columns||[]) as Col[]}
async function updateCol(token:string,b:string,i:string,c:string,value:Record<string,unknown>){const q=`mutation($boardId:ID!,$itemId:ID!,$columnId:String!,$value:JSON!){change_column_value(board_id:$boardId,item_id:$itemId,column_id:$columnId,value:$value){id}}`;return monday(token,q,{boardId:b,itemId:i,columnId:c,value:JSON.stringify(value)})}
async function updateSimple(token:string,b:string,i:string,c:string,value:string){const q=`mutation($boardId:ID!,$itemId:ID!,$columnId:String!,$value:String!){change_simple_column_value(board_id:$boardId,item_id:$itemId,column_id:$columnId,value:$value){id}}`;return monday(token,q,{boardId:b,itemId:i,columnId:c,value})}
async function monday(token:string,query:string,variables:Record<string,unknown>){const r=await fetch(mondayApiUrl,{method:"POST",headers:{"Content-Type":"application/json",Authorization:token,"api-version":"2025-04"},body:JSON.stringify({query,variables})});const p=await r.json();if(!r.ok||p.errors)throw new Error(JSON.stringify(p.errors??p));return p}
function norm(v:any){return String(v||"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toUpperCase().replace(/&/g," ET ").replace(/[^A-Z0-9]+/g," ").trim()}
function clean(v:any){return String(v||"").trim()}
function round(v:number){return Math.round((Number(v)||0)*100)/100}
function money(v:number){return `${round(v).toLocaleString("fr-FR",{minimumFractionDigits:0,maximumFractionDigits:2})} €`}
function json(data:unknown,status=200){return new Response(JSON.stringify(data),{status,headers:{...corsHeaders,"Content-Type":"application/json"}})}
